import { AdzunaSearchParams } from "./adzuna.js";

const DEFAULT_MAX_DAYS_OLD = 14;

export const ADZUNA_QUERIES: AdzunaSearchParams[] = [
  { what: "mental health", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "peer support worker", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "peer worker", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "psychologist", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "clinical psychologist", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "psychiatrist", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "mental health nurse", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "psychiatric nurse", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "registered nurse mental health", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "mental health social worker", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "counsellor", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "counselor mental health", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "psychotherapist", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "AOD worker", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "alcohol other drugs", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "drug and alcohol counsellor", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "NDIS mental health", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "NDIS support worker psychosocial", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "youth mental health", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "headspace", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "CAMHS", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "eating disorder", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "lived experience worker", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "mental health occupational therapist", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "case manager mental health", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "care coordinator mental health", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "clinical lead mental health", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "mental health educator", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "behaviour support practitioner", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "psychosocial recovery coach", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "suicide prevention", max_days_old: DEFAULT_MAX_DAYS_OLD },
  { what: "mental health support worker", max_days_old: DEFAULT_MAX_DAYS_OLD },
];
