import { getDb } from "./index";
import { initSchema } from "./schema";
import { hashSync } from "bcryptjs";

const db = getDb();
initSchema();

// Clear existing data
db.exec("DELETE FROM saved_jobs; DELETE FROM applications; DELETE FROM blog_posts; DELETE FROM jobs; DELETE FROM users;");

// Create demo users
const companyHash = hashSync("password123", 12);
const seekerHash = hashSync("password123", 12);

db.prepare("INSERT INTO users (email, password_hash, name, role, company_name) VALUES (?, ?, ?, ?, ?)").run("company@demo.com", companyHash, "Demo Company", "company", "TechCorp");
db.prepare("INSERT INTO users (email, password_hash, name, role, company_name) VALUES (?, ?, ?, ?, ?)").run("seeker@demo.com", seekerHash, "Jane Smith", "seeker", null);

const companyUser = db.prepare("SELECT id FROM users WHERE email = ?").get("company@demo.com") as { id: number };
const userId = companyUser.id;

// Seed jobs
const insertJob = db.prepare(`INSERT INTO jobs (user_id, title, company, location, category, job_type, salary_min, salary_max, description, requirements, apply_url, is_featured) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`);

const jobs = [
  [userId, "Senior Frontend Engineer", "TechCorp", "San Francisco, CA", "Engineering", "Full-time", 150000, 200000, "We're looking for a Senior Frontend Engineer to lead our UI team. You'll architect and build complex web applications using React and TypeScript.\n\nYou'll work closely with designers and backend engineers to deliver exceptional user experiences. Our tech stack includes Next.js, TypeScript, and Tailwind CSS.", "5+ years of frontend development experience\nExpert in React and TypeScript\nExperience with Next.js\nStrong CSS/Tailwind skills\nExperience leading technical projects", "https://example.com/apply", 1],
  [userId, "Product Designer", "DesignStudio", "Remote", "Design", "Full-time", 120000, 160000, "Join our design team to create beautiful, intuitive interfaces for our SaaS platform. You'll own the design process from research to final implementation.\n\nWe value designers who can think systematically and create scalable design systems.", "4+ years of product design experience\nProficiency in Figma\nExperience with design systems\nStrong portfolio showing web/mobile work\nAbility to conduct user research", "https://example.com/apply", 1],
  [userId, "Marketing Manager", "GrowthCo", "New York, NY", "Marketing", "Full-time", 90000, 130000, "Lead our marketing efforts and drive growth across all channels. You'll develop and execute marketing strategies that increase brand awareness and generate leads.\n\nThis role combines creativity with data-driven decision making.", "3+ years of marketing experience\nExperience with digital marketing channels\nStrong analytical skills\nExcellent written communication\nExperience with marketing automation tools", "https://example.com/apply", 0],
  [userId, "Data Analyst", "DataDriven", "Chicago, IL", "Data Science", "Part-time", 40000, 60000, "We need a part-time Data Analyst to help us make sense of our growing datasets. You'll create dashboards, run analyses, and present insights to stakeholders.\n\nFlexible hours — perfect for someone looking for work-life balance.", "2+ years of data analysis experience\nProficiency in SQL and Python\nExperience with visualization tools (Tableau, Looker)\nStrong communication skills\nStatistics background preferred", "https://example.com/apply", 0],
  [userId, "DevOps Engineer", "CloudScale", "Seattle, WA", "DevOps", "Remote", 140000, 180000, "Join our infrastructure team to build and maintain our cloud platform. You'll work on CI/CD pipelines, container orchestration, and monitoring systems.\n\nWe run a fully remote team across multiple time zones.", "4+ years of DevOps/SRE experience\nStrong AWS or GCP experience\nKubernetes and Docker expertise\nExperience with Terraform or Pulumi\nMonitoring and observability tools", "https://example.com/apply", 1],
  [userId, "Junior Software Developer", "StartupXYZ", "Austin, TX", "Engineering", "Full-time", 70000, 95000, "Great opportunity for a junior developer to grow their skills in a fast-paced startup environment. You'll work on full-stack features using modern web technologies.\n\nWe invest heavily in mentorship and professional development.", "1+ years of programming experience\nFamiliarity with JavaScript/TypeScript\nBasic understanding of databases\nEager to learn and grow\nCS degree or bootcamp graduate", "https://example.com/apply", 0],
  [userId, "Sales Representative", "SalesForce Inc", "Miami, FL", "Sales", "Full-time", 60000, 90000, "Drive revenue growth by building relationships with enterprise clients. You'll manage the full sales cycle from prospecting to closing.\n\nBase salary plus uncapped commission — top performers earn $150k+.", "2+ years of B2B sales experience\nExcellent communication skills\nCRM experience (Salesforce preferred)\nSelf-motivated and goal-oriented\nExperience with enterprise sales cycles", "https://example.com/apply", 0],
  [userId, "UX Researcher", "UserFirst", "Boston, MA", "Design", "Contract", 80000, 110000, "6-month contract to lead UX research for our product redesign. You'll plan and conduct user studies, synthesize findings, and drive design decisions.\n\nPossibility of conversion to full-time based on performance.", "3+ years of UX research experience\nExperience with qualitative and quantitative methods\nStrong presentation skills\nExperience with research tools (UserTesting, Maze)\nPortfolio of research case studies", "https://example.com/apply", 0],
  [userId, "Customer Support Lead", "HelpDesk Pro", "Denver, CO", "Customer Support", "Full-time", 55000, 75000, "Lead our customer support team and ensure exceptional service delivery. You'll manage a team of 5 support agents and develop processes to improve response times.\n\nWe're a growing SaaS company that puts customers first.", "3+ years of customer support experience\n1+ years in a leadership role\nExperience with helpdesk software\nExcellent problem-solving skills\nPatient and empathetic communicator", "https://example.com/apply", 0],
  [userId, "Financial Analyst", "FinCorp", "New York, NY", "Finance", "Full-time", 85000, 120000, "Analyze financial data and create models to support strategic decision-making. You'll work with the CFO and leadership team on budgeting, forecasting, and investment analysis.\n\nExcellent opportunity for career growth in corporate finance.", "2+ years of financial analysis experience\nAdvanced Excel and financial modeling skills\nExperience with ERP systems\nCFA or MBA preferred\nStrong attention to detail", "https://example.com/apply", 0],
  [userId, "Backend Engineer (Python)", "APIWorks", "Remote", "Engineering", "Full-time", 130000, 175000, "Build scalable APIs and microservices using Python and FastAPI. You'll design systems that handle millions of requests per day.\n\nFully remote position with flexible hours and excellent benefits.", "4+ years of Python backend development\nExperience with FastAPI or Django\nDatabase design (PostgreSQL, Redis)\nAPI design and documentation\nExperience with cloud services (AWS/GCP)", "https://example.com/apply", 1],
  [userId, "HR Coordinator", "PeopleFirst", "Los Angeles, CA", "Human Resources", "Full-time", 50000, 70000, "Support our HR operations including onboarding, benefits administration, and employee relations. Great entry-level HR position with room to grow.\n\nYou'll be part of a supportive team that values work-life balance.", "1+ years of HR or administrative experience\nFamiliarity with HR software (BambooHR, Workday)\nExcellent organizational skills\nStrong interpersonal skills\nHR certification preferred but not required", "https://example.com/apply", 0],
  [userId, "Content Marketing Specialist", "ContentKing", "Remote", "Marketing", "Part-time", 45000, 65000, "Create compelling content that drives organic traffic and engagement. You'll write blog posts, case studies, and social media content.\n\nPart-time role with flexible schedule — perfect for freelancers.", "2+ years of content writing experience\nSEO knowledge\nExperience with CMS platforms\nStrong research skills\nPortfolio of published work", "https://example.com/apply", 0],
  [userId, "Product Manager", "InnovateTech", "San Francisco, CA", "Product", "Full-time", 140000, 190000, "Define product strategy and roadmap for our flagship SaaS product. You'll work at the intersection of business, technology, and design.\n\nJoin a high-growth company backed by top-tier VCs.", "5+ years of product management experience\nTechnical background preferred\nExperience with agile methodologies\nStrong data analysis skills\nExcellent stakeholder management", "https://example.com/apply", 1],
  [userId, "Machine Learning Engineer", "AI Solutions", "Seattle, WA", "Data Science", "Full-time", 160000, 220000, "Build and deploy ML models that power our AI-driven products. You'll work on NLP, computer vision, and recommendation systems.\n\nCutting-edge work with access to significant compute resources.", "3+ years of ML engineering experience\nPython, PyTorch/TensorFlow\nExperience deploying models to production\nStrong math/statistics foundation\nMS or PhD in CS/ML preferred", "https://example.com/apply", 1],
  [userId, "React Native Developer", "MobileApps Co", "Austin, TX", "Engineering", "Contract", 100000, 140000, "Build cross-platform mobile apps using React Native. 6-month contract with potential for extension.\n\nYou'll work on consumer-facing apps with millions of users.", "3+ years of React Native experience\niOS and Android development knowledge\nExperience with app store deployment\nStrong JavaScript/TypeScript skills\nExperience with mobile CI/CD", "https://example.com/apply", 0],
  [userId, "Growth Marketing Intern", "LaunchPad", "Remote", "Marketing", "Internship", null, null, "Learn growth marketing from experienced mentors. You'll get hands-on experience with paid ads, email marketing, and analytics.\n\nUnpaid internship with strong learning opportunities and mentorship.", "Currently enrolled in college\nInterest in digital marketing\nBasic understanding of social media\nEager to learn\nStrong written communication", "https://example.com/apply", 0],
  [userId, "Site Reliability Engineer", "Uptime Inc", "Chicago, IL", "DevOps", "Full-time", 135000, 170000, "Keep our systems running at 99.99% uptime. You'll build monitoring, alerting, and auto-remediation systems.\n\nOn-call rotation with generous compensation for off-hours work.", "4+ years of SRE/DevOps experience\nLinux systems administration\nPrometheus/Grafana experience\nIncident management experience\nScripting (Python, Bash, Go)", "https://example.com/apply", 0],
];

const insertMany = db.transaction(() => {
  for (const job of jobs) {
    insertJob.run(...job);
  }
});
insertMany();

// Seed blog posts
const insertPost = db.prepare("INSERT INTO blog_posts (title, slug, content, excerpt, author, published_at) VALUES (?, ?, ?, ?, ?, ?)");

const posts = [
  ["10 Tips for Landing Your Dream Tech Job", "10-tips-landing-dream-tech-job", "Looking for your next tech role? Here are 10 proven strategies to help you stand out.\n\n## 1. Tailor Your Resume\nCustomize your resume for each application. Highlight relevant skills and experiences that match the job description.\n\n## 2. Build a Portfolio\nShowcase your best work. A strong portfolio speaks louder than a resume.\n\n## 3. Network Actively\nAttend meetups, conferences, and engage on LinkedIn. Many jobs are filled through referrals.\n\n## 4. Practice Coding Interviews\nUse platforms like LeetCode and HackerRank to sharpen your skills.\n\n## 5. Research the Company\nUnderstand the company's mission, products, and culture before your interview.\n\n## 6. Prepare STAR Stories\nUse the Situation, Task, Action, Result framework for behavioral questions.\n\n## 7. Follow Up\nSend a thoughtful thank-you email after every interview.\n\n## 8. Negotiate Your Offer\nDon't accept the first offer. Research market rates and negotiate confidently.\n\n## 9. Stay Current\nKeep learning new technologies and frameworks relevant to your field.\n\n## 10. Be Patient\nJob searching takes time. Stay persistent and don't get discouraged.", "Proven strategies to help you stand out in the competitive tech job market and land the role you've been dreaming of.", "Sarah Johnson", "2026-04-10"],
  ["The Rise of Remote Work: What Employers Need to Know", "rise-of-remote-work-employers-guide", "Remote work is here to stay. Here's how employers can adapt and thrive.\n\n## The New Normal\nSince 2020, remote work has transformed from a perk to an expectation. Companies that embrace it gain access to a global talent pool.\n\n## Building Remote Culture\nCulture doesn't happen by accident in remote teams. Schedule regular virtual social events, create dedicated Slack channels for non-work topics, and invest in annual retreats.\n\n## Tools for Success\nEquip your team with the right tools: Slack for communication, Zoom for meetings, Notion for documentation, and GitHub for collaboration.\n\n## Managing Performance\nFocus on outcomes, not hours. Set clear goals and trust your team to deliver.\n\n## Legal Considerations\nRemote workers in different states or countries bring tax and compliance complexity. Consult with legal experts.\n\n## The Hybrid Approach\nMany companies find success with a hybrid model — 2-3 days in office, rest remote. This balances collaboration with flexibility.", "Remote work has fundamentally changed the employment landscape. Learn how to build effective remote teams and attract top talent.", "Michael Chen", "2026-04-08"],
  ["Salary Negotiation: A Complete Guide", "salary-negotiation-complete-guide", "Don't leave money on the table. Here's how to negotiate your salary like a pro.\n\n## Do Your Research\nUse sites like Glassdoor, Levels.fyi, and Payscale to understand market rates for your role and location.\n\n## Know Your Worth\nList your accomplishments, skills, and unique value. Quantify your impact wherever possible.\n\n## Timing Matters\nNegotiate after you receive an offer, not during early interviews. You have the most leverage when they've decided they want you.\n\n## The Conversation\nExpress enthusiasm first, then state your case. 'I'm excited about this opportunity. Based on my research and experience, I was hoping for a salary in the range of X to Y.'\n\n## Beyond Base Salary\nConsider the total package: equity, signing bonus, PTO, remote work, professional development budget, and other benefits.\n\n## Practice\nRehearsal your negotiation with a friend or mentor. The more comfortable you are, the better the outcome.\n\n## Walking Away\nKnow your minimum acceptable offer before you start negotiating. Be prepared to walk away if it's not met.", "Learn proven techniques for negotiating your salary and total compensation package to maximize your earning potential.", "Emily Rodriguez", "2026-04-05"],
  ["How to Write a Job Description That Attracts Top Talent", "write-job-description-attracts-top-talent", "Your job description is your first impression. Make it count.\n\n## Start with a Hook\nOpen with what makes your company and role exciting. Skip the boring corporate boilerplate.\n\n## Be Specific About the Role\nDescribe what a typical day or week looks like. Candidates want to picture themselves in the job.\n\n## List Requirements Honestly\nOnly list truly required qualifications. Research shows women apply only when they meet 100% of requirements, while men apply at 60%.\n\n## Include Salary Range\nTransparency builds trust. Companies that list salary ranges get 30% more applications.\n\n## Highlight Growth\nTop candidates want to know how they'll develop. Mention mentorship, training, and career paths.\n\n## Showcase Culture\nDescribe your team dynamics, work style, and values. Cultural fit matters to candidates.\n\n## Keep It Scannable\nUse bullet points, headers, and short paragraphs. Most candidates scan job descriptions in under 60 seconds.", "Learn how to craft compelling job descriptions that attract qualified candidates and reduce time-to-hire.", "David Park", "2026-04-01"],
];

const insertPosts = db.transaction(() => {
  for (const post of posts) {
    insertPost.run(...post);
  }
});
insertPosts();

console.log("Seeded successfully:");
console.log(`  - ${db.prepare("SELECT COUNT(*) as c FROM users").get() ? (db.prepare("SELECT COUNT(*) as c FROM users").get() as {c:number}).c : 0} users`);
console.log(`  - ${(db.prepare("SELECT COUNT(*) as c FROM jobs").get() as {c:number}).c} jobs`);
console.log(`  - ${(db.prepare("SELECT COUNT(*) as c FROM blog_posts").get() as {c:number}).c} blog posts`);
